### ISSUE TITLE
Criar estrutura do projeto

### ISSUE THREAD

**Issue by andrerodrig** [ajsalmeida/tesseract-team-future-projectliquor#1]
Criar a estrutura do projeto de data science baseada no template **coockiecutter data science**, separando pastas específicas para data, notebooks, scripts etc:
* https://drivendata.github.io/cookiecutter-data-science/

**Comment by ajsalmeida** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Criar estrutura do projeto](https://trello.com/c/d5By7ULa/4-criar-estrutura-do-projeto)
