### ISSUE TITLE
Preparação dos dados

### ISSUE THREAD

**Issue by omadson** [ajsalmeida/tesseract-team-future-projectliquor#12]
Criei essa issue para que possamos acompanhar a etapa de preparação de dados. Esta etapa é necessária para efetuar a preparação dos conjuntos de dados que serão utilizados na etapa de modelagem. É uma das etapas mais importantes, pois ela afeta diretamente a possibilidade de bons resultados na etapa de modelagem.

Vocês deverão efetuar as tarefas seguintes (se acharem necessárias):

 - [x] #13
 - [x] #14
 - [x] #15
 - [x] #16
 - [x] #17
---
Criem um notebook com o nome `02-data-preparation.ipynb` (dentro da pasta de notebooks) e documentem o máximo necessário para que pessoas que não estão participando do processo todo também consigam entender.

**Comment by omadson** [comment]
Ah, me coloquem como revisor do PR.

**Comment by ajsalmeida** [comment]
done
