### ISSUE TITLE
Definição das perguntas a responder

### ISSUE THREAD

**Issue by ajsalmeida** [ajsalmeida/tesseract-team-future-projectliquor#4]
Analisar as variáveis e determinar quais perguntas podem ser respondidas através da análise do dataset

**Comment by ajsalmeida** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Determinar perguntas que podem ser respondidas através da análise do dataset](https://trello.com/c/9jgrdJGx/2-determinar-perguntas-que-podem-ser-respondidas-atrav%C3%A9s-da-an%C3%A1lise-do-dataset)

**Comment by ajsalmeida** [comment]
Ficou definido o seguinte:

Em quais condados onde se vendeu mais?
No condado onde se vendeu mais, quais cidades venderam mais bebida?
Em quais cidade se vendeu mais bebida?
Em que ano houve mais venda de bebidas?

**Comment by omadson** [comment]
Essa issue já foi resolvida? se sim, melhor fechar.
