### ISSUE TITLE
Identificar problemas nos dados do dataset

### ISSUE THREAD

**Issue by ajsalmeida** [ajsalmeida/tesseract-team-future-projectliquor#5]
Encontrar alguns problemas que possam existir e atrapalhar nossa análise. Tais como:

1. Valores NaN
2. Outliers
3. Diferença de upper/lower case nos valores das colunas
4. Inconsistências de valores de variáveis
5. Informações dispensáveis, como aspas, parênteses, cifrões etc

**Comment by ajsalmeida** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Identificar problemas nos dados do datset](https://trello.com/c/0TY9dFb5/3-identificar-problemas-nos-dados-do-datset)

**Comment by ajsalmeida** [comment]
Idenficamos
- valores faltantes em alguma colunas
- dados uppercase, lowercase na mesma coluna
- aspas, cifrões nos dados das colunas

**Comment by omadson** [comment]
Essa issue já foi resolvida? se sim, melhor fechar.
